# Fix Hugo Theme Configuration

## Option 1: Use Traditional Theme Installation (Recommended)

If you already have the Ananke theme in your `themes/` directory, update your `hugo.toml`:

```toml
baseURL = 'https://docs.jeejy.org'
languageCode = 'en-us'
title = 'JEEJY - Blog & Learning Hub'
theme = 'ananke'
pygmentsCodeFences = true
pygmentsStyle = "github"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Learning"
    url = "/learning/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  topic = "topics"

[params]
  author = "JEEJY"
  description = "Personal blog and learning materials"
  favicon = "favicon.ico"
  site_logo = ""
  background_color_class = "bg-black"
  featured_image = "/images/hero-bg.jpg"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]
  custom_js = ["js/main.js"]
  reading_time = true
  share_buttons = true
  toc = true
  
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/JEEJY30"
  [[params.social]]
    name = "Twitter"
    url = "https://twitter.com/yourusername"
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/yourusername"

  [params.social_share]
    twitter = true
    linkedin = true
    facebook = true
```

**Note:** Removed the `[module]` section entirely.

## Option 2: Fix Hugo Modules (Advanced)

If you want to use Hugo modules, you need to initialize your site as a module first:

### Step 1: Initialize Hugo Module
```bash
# In your project root
hugo mod init github.com/JEEJY30/docs.jeejy.org
```

### Step 2: Update hugo.toml for modules
```toml
baseURL = 'https://docs.jeejy.org'
languageCode = 'en-us'
title = 'JEEJY - Blog & Learning Hub'
pygmentsCodeFences = true
pygmentsStyle = "github"

[pagination]
  pagerSize = 10

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2
  [[menu.main]]
    name = "Learning"
    url = "/learning/"
    weight = 3
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 5

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"
  topic = "topics"

[params]
  author = "JEEJY"
  description = "Personal blog and learning materials"
  favicon = "favicon.ico"
  site_logo = ""
  background_color_class = "bg-black"
  featured_image = "/images/hero-bg.jpg"
  recent_posts_number = 3
  custom_css = ["css/custom.css"]
  custom_js = ["js/main.js"]
  reading_time = true
  share_buttons = true
  toc = true
  
  [[params.social]]
    name = "GitHub"
    url = "https://github.com/JEEJY30"
  [[params.social]]
    name = "Twitter"
    url = "https://twitter.com/yourusername"
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/yourusername"

  [params.social_share]
    twitter = true
    linkedin = true
    facebook = true

[module]
  [[module.imports]]
    path = "github.com/theNewDynamic/gohugo-theme-ananke"
```

### Step 3: Download the theme module
```bash
hugo mod get github.com/theNewDynamic/gohugo-theme-ananke
```

## Option 3: GitHub Actions Fix

If you're using GitHub Actions, add this step before building:

```yaml
- name: Setup Hugo modules
  run: |
    hugo mod init github.com/JEEJY30/docs.jeejy.org
    hugo mod get github.com/theNewDynamic/gohugo-theme-ananke
```

## Quick Fix for Your Current Setup

Based on your error, the simplest fix is **Option 1**. Just update your `hugo.toml` to remove the `[module]` section:

1. **Remove these lines** from your `hugo.toml`:
   ```toml
   [module]
     [[module.imports]]
       path = "github.com/theNewDynamic/gohugo-theme-ananke"
   ```

2. **Keep the line** `theme = 'ananke'`

3. **Make sure** you have the Ananke theme in your `themes/ananke/` directory

## Check Your Theme Installation

Verify your theme is properly installed:

```bash
# Check if theme exists
ls themes/

# Should show: ananke (or whatever your theme folder is named)
```

If you don't have the theme installed, install